spring:
  application:
    name: MODULE-SERVICE
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: modules
      port: 27017
      host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8777/eureka/

queue:
  events: q.events