spring:
  application:
    name: MODULE-SERVICE
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: modules
      port: 27017
      host: localhost
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8777/eureka/