spring:
  application:
    name: MODULE-SERVICE
  data:
    mongodb:
      authentication-database: modules
      username: module-admin
      password: module-admin
      database: modules
      port: 27017
      host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 9666

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8777/eureka/

queue:
  events: q.events